name: Go

on:
  push:
    branches:
      - "!*"
    tags:
      - "v*"
jobs:

  build:
    runs-on: ubuntu-latest
    env:
      VERSION: ${GITHUB_REF#refs/tags/}
  
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: Test
      run: make test

    - name: Build
      run: |
        TARGET=darwin make
        tar zcf amocli-${VERSION}-macos.tar.gz amocli
        rm -f amocli; TARGET=linux make
        tar zcf amocli-${VERSION}-linux.tar.gz amocli
        rm -f amocli; TARGET=windows make
        tar zcf amocli-${VERSION}-windows.tar.gz amocli.exe
        rm -f amocli.exe
    - name: Create release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${VERSION}
        release_name: ${VERSION} release
        draft: true
        prelease: true
    
    - name: Upload Release Asset
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        files: |
          amocli-${VERSION}-macos.tar.gz
          amocli-${VERSION}-linux.tar.gz
          amocli-${VERSION}-windows.tar.gz
